@echo off
echo Starting RAG Claims Assistant Demo...

echo Generating Synthetic Data...
python data_gen/generate_synthetic_claims.py

echo Starting Docker Containers...
docker-compose up -d --build

echo Waiting 10 seconds for services to start...
timeout /t 10 /nobreak

echo Running Demo Client...
pip install requests
python demo_client.py

echo Demo Complete. Access the UI at http://localhost:3000
echo Press any key to exit...
pause
